var newFollower = { event: 'follow',
  created_at: 'Wed Feb 06 07:30:25 +0000 2013',
  target: 
   { default_profile_image: true,
     id: 1110594535,
     geo_enabled: false,
     profile_background_image_url_https: 'https://si0.twimg.com/images/themes/theme1/bg.png',
     friends_count: 5,
     favourites_count: 0,
     profile_use_background_image: true,
     profile_text_color: '333333',
     id_str: '1110594535',
     profile_image_url: 'http://a0.twimg.com/sticky/default_profile_images/default_profile_1_normal.png',
     profile_image_url_https: 'https://si0.twimg.com/sticky/default_profile_images/default_profile_1_normal.png',
     utc_offset: null,
     follow_request_sent: false,
     location: null,
     name: 'Game Master',
     lang: 'en',
     profile_sidebar_border_color: 'C0DEED',
     verified: false,
     statuses_count: 0,
     protected: false,
     default_profile: true,
     is_translator: false,
     profile_background_tile: false,
     profile_sidebar_fill_color: 'DDEEF6',
     following: true,
     listed_count: 0,
     screen_name: 'questinatweet',
     profile_background_color: 'C0DEED',
     created_at: 'Tue Jan 22 04:11:29 +0000 2013',
     notifications: false,
     followers_count: 2,
     contributors_enabled: false,
     profile_background_image_url: 'http://a0.twimg.com/images/themes/theme1/bg.png',
     time_zone: null,
     description: '',
     profile_link_color: '0084B4',
     url: null },
  source: 
   { default_profile_image: true,
     id: 1097674440,
     geo_enabled: false,
     profile_background_image_url_https: 'https://si0.twimg.com/images/themes/theme1/bg.png',
     friends_count: 14,
     favourites_count: 0,
     profile_use_background_image: true,
     profile_text_color: '333333',
     id_str: '1097674440',
     profile_image_url: 'http://a0.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
     profile_image_url_https: 'https://si0.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
     utc_offset: null,
     follow_request_sent: false,
     location: null,
     name: 'Game Master',
     lang: 'en',
     profile_sidebar_border_color: 'C0DEED',
     verified: false,
     statuses_count: 1,
     protected: false,
     default_profile: true,
     is_translator: false,
     profile_background_tile: false,
     profile_sidebar_fill_color: 'DDEEF6',
     following: false,
     listed_count: 0,
     screen_name: 'quickquest',
     profile_background_color: 'C0DEED',
     created_at: 'Thu Jan 17 09:29:40 +0000 2013',
     notifications: false,
     followers_count: 0,
     contributors_enabled: false,
     profile_background_image_url: 'http://a0.twimg.com/images/themes/theme1/bg.png',
     time_zone: null,
     description: '',
     profile_link_color: '0084B4',
     url: null 
 };