var newFollower = { event: 'follow',
  created_at: 'Wed Feb 06 07:30:25 +0000 2013',
  target: 
   { default_profile_image: true,
     id: 1110594535,
     geo_enabled: false,
     profile_background_image_url_https: 'https://si0.twimg.com/images/themes/theme1/bg.png',
     friends_count: 5,
     favourites_count: 0,
     profile_use_background_image: true,
     profile_text_color: '333333',
     id_str: '1110594535',
     profile_image_url: 'http://a0.twimg.com/sticky/default_profile_images/default_profile_1_normal.png',
     profile_image_url_https: 'https://si0.twimg.com/sticky/default_profile_images/default_profile_1_normal.png',
     utc_offset: null,
     follow_request_sent: false,
     location: null,
     name: 'Game Master',
     lang: 'en',
     profile_sidebar_border_color: 'C0DEED',
     verified: false,
     statuses_count: 0,
     protected: false,
     default_profile: true,
     is_translator: false,
     profile_background_tile: false,
     profile_sidebar_fill_color: 'DDEEF6',
     following: true,
     listed_count: 0,
     screen_name: 'questinatweet',
     profile_background_color: 'C0DEED',
     created_at: 'Tue Jan 22 04:11:29 +0000 2013',
     notifications: false,
     followers_count: 2,
     contributors_enabled: false,
     profile_background_image_url: 'http://a0.twimg.com/images/themes/theme1/bg.png',
     time_zone: null,
     description: '',
     profile_link_color: '0084B4',
     url: null },
  source: 
   { default_profile_image: true,
     id: 1097674440,
     geo_enabled: false,
     profile_background_image_url_https: 'https://si0.twimg.com/images/themes/theme1/bg.png',
     friends_count: 14,
     favourites_count: 0,
     profile_use_background_image: true,
     profile_text_color: '333333',
     id_str: '1097674440',
     profile_image_url: 'http://a0.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
     profile_image_url_https: 'https://si0.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
     utc_offset: null,
     follow_request_sent: false,
     location: null,
     name: 'Game Master',
     lang: 'en',
     profile_sidebar_border_color: 'C0DEED',
     verified: false,
     statuses_count: 1,
     protected: false,
     default_profile: true,
     is_translator: false,
     profile_background_tile: false,
     profile_sidebar_fill_color: 'DDEEF6',
     following: false,
     listed_count: 0,
     screen_name: 'quickquest',
     profile_background_color: 'C0DEED',
     created_at: 'Thu Jan 17 09:29:40 +0000 2013',
     notifications: false,
     followers_count: 0,
     contributors_enabled: false,
     profile_background_image_url: 'http://a0.twimg.com/images/themes/theme1/bg.png',
     time_zone: null,
     description: '',
     profile_link_color: '0084B4',
     url: null 
 };

 var testDM = { direct_message: 
   { entities: { user_mentions: [], hashtags: [], urls: [] },
     created_at: 'Wed Feb 06 23:15:04 +0000 2013',
     id_str: '299295171173031937',
     sender_id: 16663578,
     recipient: 
      { default_profile_image: true,
        id: 1110594535,
        geo_enabled: false,
        profile_background_image_url_https: 'https://twimg0-a.akamaihd.net/images/themes/theme1/bg.png',
        friends_count: 7,
        favourites_count: 0,
        profile_use_background_image: true,
        profile_text_color: '333333',
        id_str: '1110594535',
        profile_image_url: 'http://a0.twimg.com/sticky/default_profile_images/default_profile_1_normal.png',
        utc_offset: null,
        follow_request_sent: false,
        location: null,
        name: 'Game Master',
        lang: 'en',
        profile_sidebar_border_color: 'C0DEED',
        verified: false,
        statuses_count: 0,
        protected: false,
        default_profile: true,
        profile_background_tile: false,
        profile_sidebar_fill_color: 'DDEEF6',
        is_translator: false,
        following: true,
        listed_count: 0,
        screen_name: 'questinatweet',
        profile_background_color: 'C0DEED',
        profile_image_url_https: 'https://twimg0-a.akamaihd.net/sticky/default_profile_images/default_profile_1_normal.png',
        created_at: 'Tue Jan 22 04:11:29 +0000 2013',
        notifications: false,
        followers_count: 4,
        contributors_enabled: false,
        profile_background_image_url: 'http://a0.twimg.com/images/themes/theme1/bg.png',
        time_zone: null,
        description: '',
        profile_link_color: '0084B4',
        url: null },
     sender: 
      { default_profile_image: false,
        id: 16663578,
        geo_enabled: false,
        profile_background_image_url_https: 'https://twimg0-a.akamaihd.net/profile_background_images/716985414/56568e7e7cfc5f0312f0b28946b9234d.png',
        friends_count: 357,
        favourites_count: 173,
        profile_use_background_image: false,
        profile_text_color: '666666',
        id_str: '16663578',
        profile_image_url: 'http://a0.twimg.com/profile_images/2809146576/39a08a8a44e7e3cd364c1de1b1eb82fe_normal.jpeg',
        utc_offset: 36000,
        follow_request_sent: false,
        location: 'Mountain View, CA',
        name: 'Louis Stowasser',
        lang: 'en',
        profile_sidebar_border_color: 'FFFFFF',
        verified: false,
        statuses_count: 601,
        protected: false,
        default_profile: false,
        profile_background_tile: false,
        profile_sidebar_fill_color: '252429',
        is_translator: false,
        following: false,
        listed_count: 24,
        profile_banner_url: 'https://twimg0-a.akamaihd.net/profile_banners/16663578/1353442470',
        screen_name: 'louisstow',
        profile_background_color: '1A1B1F',
        profile_image_url_https: 'https://twimg0-a.akamaihd.net/profile_images/2809146576/39a08a8a44e7e3cd364c1de1b1eb82fe_normal.jpeg',
        created_at: 'Thu Oct 09 07:54:48 +0000 2008',
        notifications: false,
        followers_count: 424,
        contributors_enabled: false,
        profile_background_image_url: 'http://a0.twimg.com/profile_background_images/716985414/56568e7e7cfc5f0312f0b28946b9234d.png',
        time_zone: 'Brisbane',
        description: 'I like all things JavaScript and HTML5. I am the creator of Crafty and work for no man.',
        profile_link_color: '2FC2EF',
        url: 'http://louisstowasser.com' },
     sender_screen_name: 'louisstow',
     recipient_id: 1110594535,
     sender_id_str: '16663578',
     text: 'roll',
     recipient_id_str: '1110594535',
     id: 299295171173031940,
     recipient_screen_name: 'questinatweet' } 
 };