var index = require("../index");

var sampleTweet = { created_at: 'Wed Feb 06 00:09:14 +0000 2013',
  id: 298946418150866940,
  id_str: '298946418150866944',
  text: '@questinatweet attack @csl_',
  source: 'web',
  truncated: false,
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: 1110594535,
  in_reply_to_user_id_str: '1110594535',
  in_reply_to_screen_name: 'questinatweet',
  user: 
   { id: 1097674440,
     id_str: '1097674440',
     name: 'Game Master',
     screen_name: 'quickquest',
     location: '',
     url: null,
     description: null,
     protected: false,
     followers_count: 0,
     friends_count: 14,
     listed_count: 0,
     created_at: 'Thu Jan 17 09:29:40 +0000 2013',
     favourites_count: 0,
     utc_offset: null,
     time_zone: null,
     geo_enabled: false,
     verified: false,
     statuses_count: 1,
     lang: 'en',
     contributors_enabled: false,
     is_translator: false,
     profile_background_color: 'C0DEED',
     profile_background_image_url: 'http://a0.twimg.com/images/themes/theme1/bg.png',
     profile_background_image_url_https: 'https://si0.twimg.com/images/themes/theme1/bg.png',
     profile_background_tile: false,
     profile_image_url: 'http://a0.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
     profile_image_url_https: 'https://si0.twimg.com/sticky/default_profile_images/default_profile_2_normal.png',
     profile_link_color: '0084B4',
     profile_sidebar_border_color: 'C0DEED',
     profile_sidebar_fill_color: 'DDEEF6',
     profile_text_color: '333333',
     profile_use_background_image: true,
     default_profile: true,
     default_profile_image: true,
     following: null,
     follow_request_sent: null,
     notifications: null },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  retweet_count: 0,
  entities: { hashtags: [], urls: [], user_mentions: [ [Object] ] },
  favorited: false,
  retweeted: false,
  lang: 'tl' 
};

console.log(index.parse(sampleTweet));